FROM oven/bun:1-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

FROM base AS runner

ARG NODE_ENV
ARG PORT
ARG PAGSMILE_APP_ID
ARG PAGSMILE_SECURITY_KEY
ARG PAGSMILE_PUBLIC_KEY
ARG PAGSMILE_ENVIRONMENT
ARG PAGSMILE_NOTIFY_URL
ARG PAGSMILE_RETURN_URL

ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV PAGSMILE_APP_ID=$PAGSMILE_APP_ID
ENV PAGSMILE_SECURITY_KEY=$PAGSMILE_SECURITY_KEY
ENV PAGSMILE_PUBLIC_KEY=$PAGSMILE_PUBLIC_KEY
ENV PAGSMILE_ENVIRONMENT=$PAGSMILE_ENVIRONMENT
ENV PAGSMILE_NOTIFY_URL=$PAGSMILE_NOTIFY_URL
ENV PAGSMILE_RETURN_URL=$PAGSMILE_RETURN_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .

USER bun
EXPOSE 3000

CMD ["bun", "run", "index.ts"]
